name: beauty_salon
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  table_calendar: ^3.0.9
  intl: ^0.18.1
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  mocktail: ^1.0.3
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true